language: node_js
node_js:
  - '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
stages:
  - coverage
  - release
jobs:
  include:
    - stage: coverage
      script: yarn lint && yarn test:ci && yarn report-coverage
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn build && yarn deploy-docs && cd dist && npx semantic-release
